version: "3"
services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra_db
    ports:
      - "9042:9042"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

  hbase:
    image: harisekhon/hbase:latest           
    container_name: hbase_db
    ports:
      - "16010:16010"   
      - "2181:2181"     
      - "9090:9090"     
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'status' | hbase shell -n >/dev/null"]
      interval: 30s
      timeout: 10s
  app:
    build: .
    container_name: node_app
    depends_on:
      - cassandra
    networks:
      - app-network
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]

  seed:
    build: .
    container_name: seed_dataset
    depends_on:
      - cassandra
      - app
    networks:
      - app-network
    command: ["npm", "run", "seed"]
    restart: "no"

networks:
  app-network:
    driver: bridge
